import { Router } from "express";
import { prisma } from "../lib/prisma";
import { requireRole, requireUser } from "../middleware/auth";
import { loadEnrolledChapter } from "../lib/enrollment";

export const contentRouter = Router();

contentRouter.use(requireUser, requireRole("STUDENT"));

// List the chapters of a pack the student is enrolled in (so they can navigate into one).
contentRouter.get("/pack/:tutorPackId", async (req, res) => {
  const pack = await prisma.tutorPack.findFirst({
    where: {
      id: req.params.tutorPackId,
      enrollments: { some: { studentId: req.user!.id } },
    },
    include: {
      chapters: {
        select: { id: true, order: true, title: true, summary: true, quiz: { select: { id: true } } },
        orderBy: { order: "asc" },
      },
    },
  });
  if (!pack) {
    res.status(404).json({ error: "Tutor pack not found" });
    return;
  }
  res.json(pack);
});

// Read-only chapter view: summary + quiz, pre-generated by an admin. Only reachable if the
// student's family has an Enrollment in the chapter's Tutor Pack.
contentRouter.get("/:chapterId", async (req, res) => {
  const chapter = await loadEnrolledChapter(req.params.chapterId, req.user!.id);
  if (!chapter) {
    res.status(404).json({ error: "Chapter not found" });
    return;
  }
  const full = await prisma.chapter.findUnique({
    where: { id: chapter.id },
    include: {
      quiz: { select: { id: true, questions: true } },
      tutorPack: { select: { tier: true, title: true } },
    },
  });
  res.json(full);
});
